meta_title: "Andinismo de Escritorio"
meta_description: "Todos los cerros de los Andes Centrales y sus ascensos más destacados"
meta_image: "metalogo.jpg" # Une image dans votre dossier app/assets/images/
meta_url: "andinismodeescritorio.cl"
instagram_account: "@andinismodeescritorio"